import re

phone_num_regex = re.compile(r'(\d{3}-)?(\d{3}-\d{4})')
mo = phone_num_regex.search('Meu número de telefone é 415-555-4242')
area_code, main_number = mo.groups()
print(area_code)

hero_regex = re.compile(r'Batman|Tina Fey')
mo1 = hero_regex.findall('Batman and Tina Fey')
mo2 = hero_regex.search('Tina Fey and Batman')
print(mo1)
print(mo2.group())
bat_regex = re.compile(r'Bat(man|mobile|copter|woman)')
mo3 = bat_regex.findall('Batman and Batwoman entered in the Batcopter because Batmobile had lost a wheel')
print(mo3)
bat_optional_regex = re.compile(r'Bat(wo)?man')
mo4 = bat_optional_regex.search('The Adventures of Batman')
mo5 = bat_optional_regex.search('The Adventures of Batwoman')
print(mo4.group(), mo5.group())
bat_zero_or_more_regex = re.compile(r'Bat(wo)*man')
mo6 = bat_zero_or_more_regex.search('Batman, the hero')
mo7 = bat_zero_or_more_regex.search('Barbara Gordon is Batwoman')
mo8 = bat_zero_or_more_regex.search('The Batwowowoman')
print(mo6.group(), mo7.group(), mo8.group())
bat_one_or_more_regex = re.compile(r'Bat(wo)+man')
mo9 = bat_one_or_more_regex.search("I'm Batman")
mo10 = bat_one_or_more_regex.search("Barbara Gordon's secret identity is not Batman, but Batwoman")
mo11 = bat_one_or_more_regex.search('The Batwowowoman')
print(mo10.group(), mo11.group())
ha_regex = re.compile(r'(Ha){3,5}') #essa é uma correspondência greedy
mo12 = ha_regex.search('The joker says HaHaHaHaHa')
print(mo12.group())
ha_regex_non_greedy = re.compile(r'(Ha){3,5}?') #essa é uma correspondência non-greedy
mo13 = ha_regex_non_greedy.search('HaHaHaHaHa')
print(mo13.group())
gifts_regex = re.compile(r'\d+\s\w+')
mo14 = gifts_regex.findall('12 drummers, 4 dogs, 11 pipers, 5 rings, 8 doves')
for gift in mo14:
    print(gift)

vowel_regex = re.compile(r'[aeiouAEIOU]')
ml2 = vowel_regex.findall('Robocop eats baby food. BABY FOOD')
for vowel in ml2:
    print(vowel)
consonant_regex = re.compile(r'[^aeiouAEIOU]')
ml3 = consonant_regex.findall('Robocopp eats baby food. BABY FOOD')
for consonant in ml3:
    print(consonant)

begins_with_hello = re.compile(r'^Hello')
mo15 = begins_with_hello.search('Hello World')
print(mo15.group())
print(begins_with_hello.search('He said hello') == None)
ends_with_number = re.compile(r'\d$')
mo16 = ends_with_number.search('Your number is 42')
print(mo16.group())
whole_string_is_num = re.compile(r'^\d+$')
mo17 = whole_string_is_num.search('9949994')
print(mo17.group())
print(whole_string_is_num.search('88ee9908r99') == None)
at_regex = re.compile(r'.at')
ats = at_regex.findall('The cat in the hat sat on the mat with a bat')
for at in ats:
    print(at)
name_regex = re.compile(r'First Name: (.*) Last Name: (.*)')
mo18 = name_regex.search('First Name: Davi Last Name: Cardoso')
first_name, last_name = mo18.groups()
print(first_name)
print(last_name)
robocop = re.compile(r'robocop', re.IGNORECASE)
mo19 = robocop.search('Robocop protects the inocent')
mo20 = robocop.search('ROBOCOP is part man, part machine, all cop')
mo21 = robocop.search('I dont like RobOcOP')
print(mo19.group(), mo20.group(), mo21.group())
names_regex = re.compile(r'Agent (\w)\w+', re.I)
so = names_regex.sub(r'\1****', 'Agent Alice gave the secret documents to agent Bob, that gave them to Agent Joe.')

print(so)